import contextlib
import asyncio as _asyncio

from .client import (
    Client,
    AsyncClient,
    GrpcClient,
    BaseSession,
    BaseAsyncSession,
    BaseSyncSession,
    RequestsSession,
    AiohttpSession,
)
from cent.requests import (
    CentRequest,
    BroadcastRequest,
    PublishRequest,
    SubscribeRequest,
    UnsubscribeRequest,
    PresenceRequest,
    PresenceStatsRequest,
    HistoryRequest,
    HistoryRemoveRequest,
    RefreshRequest,
    ChannelsRequest,
    DisconnectRequest,
    InfoRequest,
    BatchRequest,
)
from cent.results import (
    PublishResult,
    BroadcastResult,
    SubscribeResult,
    UnsubscribeResult,
    PresenceResult,
    PresenceStatsResult,
    HistoryResult,
    HistoryRemoveResult,
    RefreshResult,
    ChannelsResult,
    DisconnectResult,
    InfoResult,
    BatchResult,
)
from cent.types import (
    StreamPosition,
    ChannelOptionsOverride,
    Disconnect,
    BoolValue,
    ProcessStats,
    Node,
    Publication,
    ClientInfo,
)
from cent.exceptions import (
    CentError,
    CentNetworkError,
    CentClientDecodeError,
    CentUnauthorizedError,
    CentAPIError,
    CentTransportError,
)

with contextlib.suppress(ImportError):
    import uvloop as _uvloop

    _asyncio.set_event_loop_policy(_uvloop.EventLoopPolicy())

__all__ = (
    "AiohttpSession",
    "AsyncClient",
    "BaseAsyncSession",
    "BaseSession",
    "BaseSyncSession",
    "BatchRequest",
    "BatchResult",
    "BoolValue",
    "BroadcastRequest",
    "BroadcastResult",
    "CentAPIError",
    "CentClientDecodeError",
    "CentError",
    "CentNetworkError",
    "CentRequest",
    "CentTransportError",
    "CentUnauthorizedError",
    "ChannelOptionsOverride",
    "ChannelsRequest",
    "ChannelsResult",
    "Client",
    "ClientInfo",
    "Disconnect",
    "DisconnectRequest",
    "DisconnectResult",
    "GrpcClient",
    "HistoryRemoveRequest",
    "HistoryRemoveResult",
    "HistoryRequest",
    "HistoryResult",
    "InfoRequest",
    "InfoResult",
    "Node",
    "PresenceRequest",
    "PresenceResult",
    "PresenceStatsRequest",
    "PresenceStatsResult",
    "ProcessStats",
    "Publication",
    "PublishRequest",
    "PublishResult",
    "RefreshRequest",
    "RefreshResult",
    "RequestsSession",
    "StreamPosition",
    "SubscribeRequest",
    "SubscribeResult",
    "UnsubscribeRequest",
    "UnsubscribeResult",
    "exceptions",
    "requests",
    "types",
)
