name: Release to PyPI

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install poetry
      run: pip install poetry

    - run: poetry config pypi-token.pypi "${{ secrets.PYPI_PASSWORD }}"

    - name: Publish package
      run: poetry publish --build
